### ISSUE TITLE
How to prepare the input data and avoid introduced NAs

### ISSUE THREAD

**Issue by mpschr** [genome/bmm#1]
Hi

I am trying to apply the bmm function, but I think I am not correctly preparing the data as NAs get introduced with `digamma` and the bmm function exits with the message

```
Error in bmm.fixed.num.components(params$X, params$N.c, params$r, params$mu,  : 
  NA's inconsistent between r and X matrices
In addition: Warning messages:
1: value out of range in 'lgamma' 
2: value out of range in 'lgamma' 
3: In digamma(ubar) : NaNs produced
4: In digamma(vbar) : NaNs produced
```

I have scaled my input data is (1-dimensional) to the range between 0 and 1 and also replaced 0 with a very small double value. The rest of the parameters are the default ones prodcued by `init.bmm.parameters` and `init.bmm.parameters`.

The `print(r)` invoked by the error prints a two-column matrix exclusively containing NAs.

I don't really know what is producing this behaviour and what steps are to be taken in order to vaoid that. Also, I don't know what more could be of importance, but please let me know.

Thanks for any assistance,
Michael

**Comment by bswhite** [comment]
Hi Michael,

Would you please send a small working example of code/data that produces 
the bug?

Brian

On 9/17/15 4:43 AM, Michael P Schroeder wrote:

> Hi
> 
> I am trying to apply the bmm function, but I think I am not correctly 
> preparing the data as NAs get introduced with |digamma| and the bmm 
> function exits with the message
> 
> |Error in bmm.fixed.num.components(params$X, params$N.c, params$r, 
> params$mu, : NA's inconsistent between r and X matrices In addition: 
> Warning messages: 1: value out of range in 'lgamma' 2: value out of 
> range in 'lgamma' 3: In digamma(ubar) : NaNs produced 4: In 
> digamma(vbar) : NaNs produced |
> 
> I have scaled my input data is (1-dimensional) to the range between 0 
> and 1 and also replaced 0 with a very small double value. The rest of 
> the parameters are the default ones prodcued by |init.bmm.parameters| 
> and |init.bmm.parameters|.
> 
> The print(r) invoked by the error prints a two-column matrix 
> exclusively containing NAs.
> 
> I don't really know what is producing this behaviour and what steps 
> are to be taken in order to vaoid that. Also, I don't know what more 
> could be of importance, but please let me know.
> 
> Thanks for any assistance,
> Michael
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/genome/bmm/issues/1.

## 

Brian White, PhD
Assistant Professor
Department of Medicine, Oncology Division / McDonnell Genome Institute
Washington University School of Medicine

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by mpschr** [comment]
Hi 

I just figured out what is causing the problem.

If one of the values that are to be clustered are 0 or 1 then the NA-matrix is produced. Of course I get either or both  if I do scale the data before feeding them into `bmm`.

Anyways, here below I submit a small working example so you can test it. And also, since I am not an expert, please tell me if I am doing something terribly wrong creating the parameters.

```
set.seed(10)
tocluster = c(runif(150, min=0.1,max=0.6),runif(150, min=0.4,max=0.9) )

## Comment the following two lines in order
## to make the example work
tocluster[1] = 1
tocluster[2] = 0

initialClusters = 2
tocluster[which(tocluster==1)]
hyperparams <- init.bmm.hyperparameters(as.matrix(tocluster), initialClusters)
params = init.bmm.parameters(as.matrix(tocluster), 
                             initialClusters, 
                             hyperparams$mu0,
                             hyperparams$alpha0,
                             hyperparams$nu0,
                             hyperparams$beta0,
                             hyperparams$c0)

params$X = as.matrix(tocluster)
params$N.c = initialClusters

## DOES NOT WORK with 0 and 1 values in params$X
res = bmm(params$X, params$N.c, params$r, params$mu,
    params$alpha, params$nu, params$beta, params$c, 
    params$E.pi, mu0=hyperparams$mu0,  c0=hyperparams$c0,
    alpha0=hyperparams$alpha0, beta0=hyperparams$beta0,
    nu0=hyperparams$nu0)

```

Best,
Michael

**Comment by SUFang-Jian** [comment]
你的数据有0 或1。把 0或1的样本数据去除就好啦。
