### ISSUE TITLE
Install script invokes /bin/gtar

### ISSUE THREAD

**Issue by tedtoal** [genome/bmm#2]
On my Ubuntu system, installation using the R command "install_github("genome/bmm")" fails because the install script tries to run /bin/gtar, which does not exist.  I do not have the ability to install this or request that it be installed in the /bin directory.  The install script should just refer to it as "gtar", then I could install it locally and put it on my path.

**Comment by chrisamiller** [comment]
The "install_github" command is through the "devtools" package, so you'll have to submit a bug to them.
