### ISSUE TITLE
Installing using `install_github("genome/bmm")` command

### ISSUE THREAD

**Issue by jaebird123** [genome/bmm#4]
I get the following error when installing using the `install_github("genome/bmm")` command
```
* installing *source* package 'bmm' ...
** R
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'gtable'
Error : package 'ggplot2' could not be loaded
ERROR: lazy loading failed for package 'bmm'
```
Any reason why this might be? Thank you for your help.

**Comment by chrisamiller** [comment]
I'm unable to replicate the error. Can you install ggplot2 by hand, then try again?
```
install.packages('ggplot2', dep = TRUE)
```
if that fails, maybe try:
```
install.packages('gtable')
install.packages('ggplot2', dep = TRUE)
```

**Comment by jaebird123** [comment]
Great! Thanks for the info! I am new to R and didn't realize how package installation worked. Thanks for the info and the quick response!
